#########################################
# NB6666 Ruleset
# Last Updated: 2026-08-04T00:00:00.000Z
# Size: 28
# License: AGPL 3.0
#
# This file contains domains of Claude.
#########################################

# Claude / Anthropic 核心域名
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,claude.com
DOMAIN-SUFFIX,clau.de
DOMAIN-SUFFIX,claudemcpclient.com
DOMAIN-SUFFIX,claudemcpcontent.com
DOMAIN-SUFFIX,claudeusercontent.com

# CDN / 静态资源
DOMAIN,servd-anthropic-website.b-cdn.net
DOMAIN,anthropic.com.cdn.cloudflare.net

# 认证 / 内容
DOMAIN,anthropic.auth0.com
DOMAIN,anthropic-com.ghost.io

# 监控 / 遥测
DOMAIN-SUFFIX,sentry.io
DOMAIN-SUFFIX,statsigapi.net
DOMAIN,browser-intake-us5-datadoghq.com
DOMAIN-KEYWORD,datadog
DOMAIN-KEYWORD,sift

# 客服 / 第三方组件
DOMAIN-SUFFIX,intercom.io
DOMAIN-SUFFIX,intercomcdn.com
DOMAIN,cdn.usefathom.com
DOMAIN-SUFFIX,doubleclick.net
DOMAIN-SUFFIX,doubleclick.net
DOMAIN-SUFFIX,googletagmanager.com

# 应用进程
PROCESS-NAME,claude

# IP 段 / ASN 兜底
IP-CIDR,160.79.104.0/21,no-resolve
IP-CIDR6,2607:6bc0::/32,no-resolve
IP-ASN,399358,no-resolve

# Claude App
PROCESS-NAME,"/Applications/Claude.app/Contents/Frameworks/Claude Helper.app/Contents/MacOS/Claude Helper"
PROCESS-NAME,/Applications/Claude.app/

# Claude 最后兜底以及 IP 测试
DOMAIN-SUFFIX,myip.la
DOMAIN-KEYWORD,anthropic
DOMAIN-KEYWORD,claude
