# Cursor 核心域名
DOMAIN-SUFFIX,api2.cursor.sh
DOMAIN-SUFFIX,api3.cursor.sh
DOMAIN-SUFFIX,api4.cursor.sh
DOMAIN-SUFFIX,api5.cursor.sh
DOMAIN-SUFFIX,authentication.cursor.sh
DOMAIN-SUFFIX,authenticator.cursor.sh
DOMAIN-SUFFIX,marketplace.cursorapi.com
DOMAIN-SUFFIX,cursor-cdn.com
DOMAIN-SUFFIX,downloads.cursor.com
DOMAIN-SUFFIX,cursor.com
DOMAIN-SUFFIX,cursor.sh
DOMAIN-KEYWORD,cursor
  
# Cursor 核心进程
PROCESS-NAME,"/Applications/Cursor.app"
PROCESS-NAME,"/Applications/Cursor.app/Contents/Frameworks/Cursor Helper.app/Contents/MacOS/Cursor Helper"
PROCESS-NAME,"/Applications/Cursor.app/Contents/Frameworks/Cursor Helper (Plugin).app/Contents/MacOS/Cursor Helper (Plugin)"
PROCESS-NAME,"Cursor"


# Grok
DOMAIN-SUFFIX,grok.com
DOMAIN-SUFFIX,grok.x.com
DOMAIN-SUFFIX,x.ai
DOMAIN-SUFFIX,grokipedia.com
DOMAIN-SUFFIX,grokusercontent.com
DOMAIN-KEYWORD,grok

PROCESS-NAME,"Grok"
PROCESS-NAME,"/Applications/Grok Bot.app/Contents/MacOS/Grok Bot"
PROCESS-NAME,"/Applications/Grok Bot.app/Contents/Frameworks/Grok Bot Helper.app/Contents/MacOS/Grok Bot Helper"

# Antigravity
PROCESS-NAME,/Applications/Antigravity.app/
PROCESS-NAME,/Applications/Antigravity.app/Contents/Resources/bin/language_server
